In [1]:
import pandas as pd
import os

In [2]:
DATA_ROOT = "/Users/vidyashreeashwathnarayana/Coding/Data/M5Data"

In [3]:
cal_df = pd.read_csv(os.path.join(DATA_ROOT, "calendar.csv"))
cal_df.head(3)

,date,wm_yr_wk,weekday,wday,month,year,d,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI
0,2011-01-29,11101,Saturday,1,1,2011,d_1,NaN,NaN,NaN,NaN,0,0,0
1,2011-01-30,11101,Sunday,2,1,2011,d_2,NaN,NaN,NaN,NaN,0,0,0
2,2011-01-31,11101,Monday,3,1,2011,d_3,NaN,NaN,NaN,NaN,0,0,0

In [4]:
sales_df = pd.read_csv(os.path.join(DATA_ROOT, "sales_train_validation.csv"))
sales_df.head(3)

,id,item_id,dept_id,cat_id,store_id,state_id,d_1,d_2,d_3,d_4,...,d_1904,d_1905,d_1906,d_1907,d_1908,d_1909,d_1910,d_1911,d_1912,d_1913
0,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,1,3,0,1,1,1,3,0,1,1
1,HOBBIES_1_002_CA_1_validation,HOBBIES_1_002,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2,HOBBIES_1_003_CA_1_validation,HOBBIES_1_003,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,2,1,2,1,1,1,0,1,1,1

In [5]:
sales_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30490 entries, 0 to 30489
Columns: 1919 entries, id to d_1913
dtypes: int64(1913), str(6)
memory usage: 448.2 MB

In [6]:
sales_df.describe()

,d_1,d_2,d_3,d_4,d_5,d_6,d_7,d_8,d_9,d_10,...,d_1904,d_1905,d_1906,d_1907,d_1908,d_1909,d_1910,d_1911,d_1912,d_1913
count,30490.000000,30490.000000,30490.000000,30490.000000,30490.000000,30490.000000,30490.000000,30490.000000,30490.000000,30490.000000,...,30490.000000,30490.000000,30490.000000,30490.000000,30490.000000,30490.000000,30490.000000,30490.000000,30490.000000,30490.000000
mean,1.070220,1.041292,0.780026,0.833454,0.627944,0.958052,0.918662,1.244080,1.073663,0.838701,...,1.370581,1.586159,1.693670,1.248245,1.232207,1.159167,1.149000,1.328862,1.605838,1.633158
std,5.126689,5.365468,3.667454,4.415141,3.379344,4.785947,5.059495,6.617729,5.917204,4.206199,...,3.740017,4.097191,4.359809,3.276925,3.125471,2.876026,2.950364,3.358012,4.089422,3.812248
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.000000,2.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000,2.000000
max,360.000000,436.000000,207.000000,323.000000,296.000000,314.000000,316.000000,370.000000,385.000000,353.000000,...,129.000000,160.000000,204.000000,98.000000,100.000000,88.000000,77.000000,141.000000,171.000000,130.000000

In [9]:
for row in sales_df.head(3).itertuples():
    print(row)

Pandas(Index=0, id='HOBBIES_1_001_CA_1_validation', item_id='HOBBIES_1_001', dept_id='HOBBIES_1', cat_id='HOBBIES', store_id='CA_1', state_id='CA', d_1=0, d_2=0, d_3=0, d_4=0, d_5=0, d_6=0, d_7=0, d_8=0, d_9=0, d_10=0, d_11=0, d_12=0, d_13=0, d_14=0, d_15=0, d_16=0, d_17=0, d_18=0, d_19=0, d_20=0, d_21=0, d_22=0, d_23=0, d_24=0, d_25=0, d_26=0, d_27=0, d_28=0, d_29=0, d_30=0, d_31=0, d_32=0, d_33=0, d_34=0, d_35=0, d_36=0, d_37=0, d_38=0, d_39=0, d_40=0, d_41=0, d_42=0, d_43=0, d_44=0, d_45=0, d_46=0, d_47=0, d_48=0, d_49=0, d_50=0, d_51=0, d_52=0, d_53=0, d_54=0, d_55=0, d_56=0, d_57=0, d_58=0, d_59=0, d_60=0, d_61=0, d_62=0, d_63=0, d_64=0, d_65=0, d_66=0, d_67=0, d_68=0, d_69=0, d_70=0, d_71=0, d_72=0, d_73=0, d_74=0, d_75=0, d_76=0, d_77=0, d_78=0, d_79=0, d_80=0, d_81=0, d_82=0, d_83=0, d_84=0, d_85=0, d_86=0, d_87=0, d_88=0, d_89=0, d_90=0, d_91=0, d_92=0, d_93=0, d_94=0, d_95=0, d_96=0, d_97=0, d_98=0, d_99=0, d_100=0, d_101=0, d_102=0, d_103=0, d_104=0, d_105=0, d_106=0, d_107=0, d_108=0, d_109=0, d_110=0, d_111=0, d_112=0, d_113=0, d_114=0, d_115=0, d_116=0, d_117=0, d_118=0, d_119=0, d_120=0, d_121=0, d_122=0, d_123=0, d_124=0, d_125=0, d_126=0, d_127=0, d_128=0, d_129=0, d_130=0, d_131=0, d_132=0, d_133=0, d_134=0, d_135=0, d_136=0, d_137=0, d_138=0, d_139=0, d_140=0, d_141=0, d_142=0, d_143=0, d_144=0, d_145=0, d_146=0, d_147=0, d_148=0, d_149=0, d_150=0, d_151=0, d_152=0, d_153=0, d_154=0, d_155=0, d_156=0, d_157=0, d_158=0, d_159=0, d_160=0, d_161=0, d_162=0, d_163=0, d_164=0, d_165=0, d_166=0, d_167=0, d_168=0, d_169=0, d_170=0, d_171=0, d_172=0, d_173=0, d_174=0, d_175=0, d_176=0, d_177=0, d_178=0, d_179=0, d_180=0, d_181=0, d_182=0, d_183=0, d_184=0, d_185=0, d_186=0, d_187=0, d_188=0, d_189=0, d_190=0, d_191=0, d_192=0, d_193=0, d_194=0, d_195=0, d_196=0, d_197=0, d_198=0, d_199=0, d_200=0, d_201=0, d_202=0, d_203=0, d_204=0, d_205=0, d_206=0, d_207=0, d_208=0, d_209=0, d_210=0, d_211=0, d_212=0, d_213=0, d_214=0, d_215=0, d_216=0, d_217=0, d_218=0, d_219=0, d_220=0, d_221=0, d_222=0, d_223=0, d_224=0, d_225=0, d_226=0, d_227=0, d_228=0, d_229=0, d_230=0, d_231=0, d_232=0, d_233=0, d_234=0, d_235=0, d_236=0, d_237=0, d_238=0, d_239=0, d_240=0, d_241=0, d_242=0, d_243=0, d_244=0, d_245=0, d_246=0, d_247=0, d_248=0, d_249=0, d_250=0, d_251=0, d_252=0, d_253=0, d_254=0, d_255=0, d_256=0, d_257=0, d_258=0, d_259=0, d_260=0, d_261=0, d_262=0, d_263=0, d_264=0, d_265=0, d_266=0, d_267=0, d_268=0, d_269=0, d_270=0, d_271=0, d_272=0, d_273=0, d_274=0, d_275=0, d_276=0, d_277=0, d_278=0, d_279=0, d_280=0, d_281=0, d_282=0, d_283=0, d_284=0, d_285=0, d_286=0, d_287=0, d_288=0, d_289=0, d_290=0, d_291=0, d_292=0, d_293=0, d_294=0, d_295=0, d_296=0, d_297=0, d_298=0, d_299=0, d_300=0, d_301=0, d_302=0, d_303=0, d_304=0, d_305=0, d_306=0, d_307=0, d_308=0, d_309=0, d_310=0, d_311=0, d_312=0, d_313=0, d_314=0, d_315=0, d_316=0, d_317=0, d_318=0, d_319=0, d_320=0, d_321=0, d_322=0, d_323=0, d_324=0, d_325=0, d_326=0, d_327=0, d_328=0, d_329=0, d_330=0, d_331=0, d_332=0, d_333=0, d_334=0, d_335=0, d_336=0, d_337=0, d_338=0, d_339=0, d_340=0, d_341=0, d_342=0, d_343=0, d_344=0, d_345=0, d_346=0, d_347=0, d_348=0, d_349=0, d_350=0, d_351=0, d_352=0, d_353=0, d_354=0, d_355=0, d_356=0, d_357=0, d_358=0, d_359=0, d_360=0, d_361=0, d_362=0, d_363=0, d_364=0, d_365=0, d_366=0, d_367=0, d_368=0, d_369=0, d_370=0, d_371=0, d_372=0, d_373=0, d_374=0, d_375=0, d_376=0, d_377=0, d_378=0, d_379=0, d_380=0, d_381=0, d_382=0, d_383=0, d_384=0, d_385=0, d_386=0, d_387=0, d_388=0, d_389=0, d_390=0, d_391=0, d_392=0, d_393=0, d_394=0, d_395=0, d_396=0, d_397=0, d_398=0, d_399=0, d_400=0, d_401=0, d_402=0, d_403=0, d_404=0, d_405=0, d_406=0, d_407=0, d_408=0, d_409=0, d_410=0, d_411=0, d_412=0, d_413=0, d_414=0, d_415=0, d_416=0, d_417=0, d_418=0, d_419=0, d_420=0, d_421=0, d_422=0, d_423=0, d_424=0, d_425=0, d_426=0, d_427=0, d_428=0, d_429=0, d_430=0, d_431=0, d_432=0, d_433=0, d_434=0, d_435=0, d_436=0, d_437=0, d_438=0, d_439=0, d_440=0, d_441=0, d_442=0, d_443=0, d_444=0, d_445=0, d_446=0, d_447=0, d_448=0, d_449=0, d_450=0, d_451=0, d_452=0, d_453=0, d_454=0, d_455=0, d_456=0, d_457=0, d_458=0, d_459=0, d_460=0, d_461=0, d_462=0, d_463=0, d_464=0, d_465=0, d_466=0, d_467=0, d_468=0, d_469=0, d_470=0, d_471=0, d_472=0, d_473=0, d_474=0, d_475=0, d_476=0, d_477=0, d_478=0, d_479=0, d_480=0, d_481=0, d_482=0, d_483=0, d_484=0, d_485=0, d_486=0, d_487=0, d_488=0, d_489=0, d_490=0, d_491=0, d_492=0, d_493=0, d_494=0, d_495=0, d_496=0, d_497=0, d_498=0, d_499=0, d_500=0, d_501=0, d_502=0, d_503=0, d_504=0, d_505=0, d_506=0, d_507=0, d_508=0, d_509=0, d_510=0, d_511=0, d_512=0, d_513=0, d_514=0, d_515=0, d_516=0, d_517=0, d_518=0, d_519=0, d_520=0, d_521=0, d_522=0, d_523=0, d_524=0, d_525=0, d_526=0, d_527=0, d_528=0, d_529=0, d_530=0, d_531=0, d_532=0, d_533=0, d_534=0, d_535=0, d_536=0, d_537=0, d_538=0, d_539=0, d_540=0, d_541=0, d_542=0, d_543=0, d_544=0, d_545=0, d_546=0, d_547=0, d_548=0, d_549=0, d_550=0, d_551=0, d_552=0, d_553=0, d_554=0, d_555=0, d_556=0, d_557=0, d_558=0, d_559=0, d_560=0, d_561=0, d_562=0, d_563=0, d_564=0, d_565=0, d_566=0, d_567=0, d_568=0, d_569=0, d_570=0, d_571=0, d_572=0, d_573=0, d_574=0, d_575=0, d_576=0, d_577=0, d_578=0, d_579=0, d_580=0, d_581=0, d_582=0, d_583=0, d_584=0, d_585=0, d_586=0, d_587=0, d_588=0, d_589=0, d_590=0, d_591=0, d_592=0, d_593=0, d_594=0, d_595=0, d_596=0, d_597=0, d_598=0, d_599=0, d_600=0, d_601=0, d_602=0, d_603=0, d_604=0, d_605=0, d_606=0, d_607=0, d_608=0, d_609=0, d_610=0, d_611=0, d_612=0, d_613=0, d_614=0, d_615=0, d_616=0, d_617=0, d_618=0, d_619=0, d_620=0, d_621=0, d_622=0, d_623=0, d_624=0, d_625=0, d_626=0, d_627=0, d_628=0, d_629=0, d_630=0, d_631=0, d_632=0, d_633=0, d_634=0, d_635=0, d_636=0, d_637=0, d_638=0, d_639=0, d_640=0, d_641=0, d_642=0, d_643=0, d_644=0, d_645=0, d_646=0, d_647=0, d_648=0, d_649=0, d_650=0, d_651=0, d_652=0, d_653=0, d_654=0, d_655=0, d_656=0, d_657=0, d_658=0, d_659=0, d_660=0, d_661=0, d_662=0, d_663=0, d_664=0, d_665=0, d_666=0, d_667=0, d_668=0, d_669=0, d_670=0, d_671=0, d_672=0, d_673=0, d_674=0, d_675=0, d_676=0, d_677=0, d_678=0, d_679=0, d_680=0, d_681=0, d_682=0, d_683=0, d_684=0, d_685=0, d_686=0, d_687=0, d_688=0, d_689=0, d_690=0, d_691=0, d_692=0, d_693=0, d_694=0, d_695=0, d_696=0, d_697=0, d_698=0, d_699=0, d_700=0, d_701=0, d_702=0, d_703=0, d_704=0, d_705=0, d_706=0, d_707=0, d_708=0, d_709=0, d_710=0, d_711=0, d_712=0, d_713=0, d_714=0, d_715=0, d_716=0, d_717=0, d_718=0, d_719=0, d_720=0, d_721=0, d_722=0, d_723=0, d_724=0, d_725=0, d_726=0, d_727=0, d_728=0, d_729=0, d_730=0, d_731=0, d_732=0, d_733=0, d_734=0, d_735=0, d_736=0, d_737=0, d_738=0, d_739=0, d_740=0, d_741=0, d_742=0, d_743=0, d_744=0, d_745=0, d_746=0, d_747=0, d_748=0, d_749=0, d_750=0, d_751=0, d_752=0, d_753=0, d_754=0, d_755=0, d_756=0, d_757=0, d_758=0, d_759=0, d_760=0, d_761=0, d_762=0, d_763=0, d_764=0, d_765=0, d_766=0, d_767=0, d_768=0, d_769=0, d_770=0, d_771=0, d_772=0, d_773=0, d_774=0, d_775=0, d_776=0, d_777=0, d_778=0, d_779=0, d_780=0, d_781=0, d_782=0, d_783=0, d_784=0, d_785=0, d_786=0, d_787=0, d_788=0, d_789=0, d_790=0, d_791=0, d_792=0, d_793=0, d_794=0, d_795=0, d_796=0, d_797=0, d_798=0, d_799=0, d_800=0, d_801=0, d_802=0, d_803=0, d_804=0, d_805=0, d_806=0, d_807=0, d_808=0, d_809=0, d_810=0, d_811=0, d_812=0, d_813=0, d_814=0, d_815=0, d_816=0, d_817=0, d_818=0, d_819=0, d_820=0, d_821=0, d_822=0, d_823=0, d_824=0, d_825=0, d_826=0, d_827=0, d_828=0, d_829=0, d_830=0, d_831=0, d_832=0, d_833=0, d_834=0, d_835=0, d_836=0, d_837=0, d_838=0, d_839=0, d_840=0, d_841=0, d_842=0, d_843=0, d_844=0, d_845=0, d_846=0, d_847=0, d_848=0, d_849=0, d_850=0, d_851=0, d_852=0, d_853=0, d_854=0, d_855=0, d_856=0, d_857=0, d_858=0, d_859=0, d_860=0, d_861=0, d_862=0, d_863=0, d_864=0, d_865=0, d_866=0, d_867=0, d_868=0, d_869=0, d_870=0, d_871=0, d_872=0, d_873=0, d_874=0, d_875=0, d_876=0, d_877=0, d_878=0, d_879=0, d_880=0, d_881=0, d_882=0, d_883=0, d_884=0, d_885=0, d_886=0, d_887=0, d_888=0, d_889=0, d_890=0, d_891=0, d_892=0, d_893=0, d_894=0, d_895=0, d_896=0, d_897=0, d_898=0, d_899=0, d_900=0, d_901=0, d_902=1, d_903=0, d_904=0, d_905=0, d_906=0, d_907=0, d_908=0, d_909=0, d_910=0, d_911=0, d_912=0, d_913=0, d_914=0, d_915=0, d_916=0, d_917=2, d_918=0, d_919=1, d_920=1, d_921=0, d_922=0, d_923=0, d_924=0, d_925=0, d_926=1, d_927=2, d_928=1, d_929=0, d_930=1, d_931=1, d_932=0, d_933=0, d_934=0, d_935=1, d_936=0, d_937=0, d_938=0, d_939=0, d_940=0, d_941=0, d_942=0, d_943=1, d_944=0, d_945=1, d_946=0, d_947=0, d_948=2, d_949=1, d_950=0, d_951=0, d_952=0, d_953=2, d_954=0, d_955=0, d_956=0, d_957=0, d_958=0, d_959=1, d_960=0, d_961=0, d_962=0, d_963=1, d_964=0, d_965=1, d_966=2, d_967=1, d_968=1, d_969=0, d_970=0, d_971=0, d_972=0, d_973=1, d_974=0, d_975=0, d_976=1, d_977=2, d_978=0, d_979=1, d_980=0, d_981=0, d_982=1, d_983=0, d_984=1, d_985=0, d_986=1, d_987=0, d_988=1, d_989=0, d_990=1, d_991=0, d_992=0, d_993=0, d_994=0, d_995=1, d_996=0, d_997=0, d_998=0, d_999=0, d_1000=0, d_1001=2, d_1002=2, d_1003=0, d_1004=1, d_1005=1, d_1006=0, d_1007=0, d_1008=0, d_1009=1, d_1010=1, d_1011=0, d_1012=1, d_1013=1, d_1014=1, d_1015=1, d_1016=0, d_1017=2, d_1018=3, d_1019=1, d_1020=1, d_1021=0, d_1022=0, d_1023=0, d_1024=0, d_1025=0, d_1026=1, d_1027=0, d_1028=0, d_1029=0, d_1030=0, d_1031=2, d_1032=1, d_1033=0, d_1034=0, d_1035=1, d_1036=1, d_1037=2, d_1038=1, d_1039=1, d_1040=0, d_1041=1, d_1042=0, d_1043=1, d_1044=1, d_1045=0, d_1046=1, d_1047=1, d_1048=0, d_1049=3, d_1050=0, d_1051=0, d_1052=3, d_1053=0, d_1054=1, d_1055=1, d_1056=2, d_1057=0, d_1058=1, d_1059=1, d_1060=0, d_1061=1, d_1062=0, d_1063=0, d_1064=0, d_1065=0, d_1066=0, d_1067=0, d_1068=0, d_1069=1, d_1070=1, d_1071=0, d_1072=0, d_1073=0, d_1074=0, d_1075=0, d_1076=1, d_1077=2, d_1078=0, d_1079=0, d_1080=1, d_1081=0, d_1082=2, d_1083=0, d_1084=0, d_1085=0, d_1086=0, d_1087=0, d_1088=0, d_1089=1, d_1090=0, d_1091=1, d_1092=0, d_1093=1, d_1094=1, d_1095=0, d_1096=0, d_1097=0, d_1098=0, d_1099=0, d_1100=1, d_1101=0, d_1102=0, d_1103=0, d_1104=0, d_1105=0, d_1106=1, d_1107=2, d_1108=0, d_1109=0, d_1110=0, d_1111=0, d_1112=0, d_1113=0, d_1114=1, d_1115=2, d_1116=0, d_1117=0, d_1118=0, d_1119=2, d_1120=1, d_1121=2, d_1122=0, d_1123=0, d_1124=1, d_1125=0, d_1126=0, d_1127=0, d_1128=1, d_1129=0, d_1130=0, d_1131=1, d_1132=0, d_1133=0, d_1134=0, d_1135=0, d_1136=1, d_1137=0, d_1138=0, d_1139=0, d_1140=0, d_1141=0, d_1142=0, d_1143=1, d_1144=0, d_1145=1, d_1146=0, d_1147=1, d_1148=1, d_1149=1, d_1150=0, d_1151=2, d_1152=0, d_1153=1, d_1154=0, d_1155=0, d_1156=0, d_1157=0, d_1158=0, d_1159=0, d_1160=0, d_1161=0, d_1162=0, d_1163=0, d_1164=0, d_1165=1, d_1166=1, d_1167=1, d_1168=0, d_1169=1, d_1170=0, d_1171=0, d_1172=0, d_1173=0, d_1174=0, d_1175=1, d_1176=1, d_1177=2, d_1178=0, d_1179=1, d_1180=0, d_1181=0, d_1182=0, d_1183=0, d_1184=0, d_1185=1, d_1186=0, d_1187=1, d_1188=0, d_1189=0, d_1190=0, d_1191=0, d_1192=1, d_1193=0, d_1194=0, d_1195=0, d_1196=0, d_1197=0, d_1198=0, d_1199=1, d_1200=0, d_1201=0, d_1202=0, d_1203=0, d_1204=0, d_1205=1, d_1206=1, d_1207=0, d_1208=2, d_1209=0, d_1210=0, d_1211=1, d_1212=0, d_1213=0, d_1214=0, d_1215=1, d_1216=0, d_1217=1, d_1218=0, d_1219=0, d_1220=0, d_1221=0, d_1222=1, d_1223=0, d_1224=1, d_1225=0, d_1226=1, d_1227=0, d_1228=0, d_1229=1, d_1230=0, d_1231=0, d_1232=1, d_1233=1, d_1234=2, d_1235=0, d_1236=1, d_1237=0, d_1238=0, d_1239=0, d_1240=0, d_1241=0, d_1242=0, d_1243=0, d_1244=0, d_1245=3, d_1246=1, d_1247=2, d_1248=2, d_1249=1, d_1250=1, d_1251=0, d_1252=0, d_1253=2, d_1254=0, d_1255=0, d_1256=0, d_1257=0, d_1258=1, d_1259=0, d_1260=1, d_1261=0, d_1262=0, d_1263=0, d_1264=1, d_1265=1, d_1266=0, d_1267=3, d_1268=1, d_1269=0, d_1270=0, d_1271=0, d_1272=0, d_1273=0, d_1274=1, d_1275=0, d_1276=1, d_1277=1, d_1278=1, d_1279=0, d_1280=0, d_1281=0, d_1282=0, d_1283=2, d_1284=0, d_1285=0, d_1286=2, d_1287=0, d_1288=0, d_1289=0, d_1290=1, d_1291=0, d_1292=0, d_1293=0, d_1294=0, d_1295=0, d_1296=4, d_1297=0, d_1298=0, d_1299=2, d_1300=1, d_1301=0, d_1302=0, d_1303=0, d_1304=0, d_1305=0, d_1306=1, d_1307=0, d_1308=0, d_1309=0, d_1310=0, d_1311=0, d_1312=4, d_1313=0, d_1314=1, d_1315=0, d_1316=1, d_1317=2, d_1318=2, d_1319=0, d_1320=0, d_1321=0, d_1322=0, d_1323=2, d_1324=1, d_1325=1, d_1326=1, d_1327=1, d_1328=1, d_1329=0, d_1330=0, d_1331=1, d_1332=0, d_1333=0, d_1334=1, d_1335=0, d_1336=0, d_1337=0, d_1338=1, d_1339=1, d_1340=0, d_1341=1, d_1342=2, d_1343=0, d_1344=0, d_1345=2, d_1346=0, d_1347=1, d_1348=3, d_1349=1, d_1350=0, d_1351=0, d_1352=1, d_1353=0, d_1354=0, d_1355=1, d_1356=0, d_1357=0, d_1358=0, d_1359=0, d_1360=0, d_1361=1, d_1362=0, d_1363=0, d_1364=1, d_1365=0, d_1366=1, d_1367=1, d_1368=0, d_1369=1, d_1370=1, d_1371=0, d_1372=0, d_1373=1, d_1374=1, d_1375=1, d_1376=0, d_1377=0, d_1378=0, d_1379=0, d_1380=0, d_1381=2, d_1382=0, d_1383=0, d_1384=0, d_1385=0, d_1386=3, d_1387=0, d_1388=2, d_1389=0, d_1390=0, d_1391=0, d_1392=0, d_1393=3, d_1394=2, d_1395=0, d_1396=2, d_1397=0, d_1398=0, d_1399=2, d_1400=0, d_1401=0, d_1402=0, d_1403=0, d_1404=3, d_1405=0, d_1406=1, d_1407=1, d_1408=1, d_1409=0, d_1410=1, d_1411=0, d_1412=1, d_1413=0, d_1414=0, d_1415=2, d_1416=4, d_1417=0, d_1418=0, d_1419=0, d_1420=0, d_1421=0, d_1422=2, d_1423=0, d_1424=0, d_1425=1, d_1426=0, d_1427=0, d_1428=1, d_1429=1, d_1430=5, d_1431=1, d_1432=1, d_1433=0, d_1434=0, d_1435=0, d_1436=0, d_1437=0, d_1438=0, d_1439=0, d_1440=0, d_1441=2, d_1442=1, d_1443=1, d_1444=0, d_1445=2, d_1446=0, d_1447=2, d_1448=1, d_1449=0, d_1450=1, d_1451=0, d_1452=1, d_1453=1, d_1454=0, d_1455=0, d_1456=0, d_1457=2, d_1458=1, d_1459=1, d_1460=0, d_1461=0, d_1462=1, d_1463=0, d_1464=3, d_1465=0, d_1466=0, d_1467=0, d_1468=1, d_1469=0, d_1470=0, d_1471=2, d_1472=1, d_1473=0, d_1474=1, d_1475=0, d_1476=0, d_1477=3, d_1478=3, d_1479=0, d_1480=0, d_1481=0, d_1482=0, d_1483=0, d_1484=0, d_1485=0, d_1486=1, d_1487=1, d_1488=1, d_1489=0, d_1490=2, d_1491=2, d_1492=2, d_1493=0, d_1494=0, d_1495=1, d_1496=0, d_1497=0, d_1498=1, d_1499=3, d_1500=0, d_1501=0, d_1502=0, d_1503=1, d_1504=1, d_1505=0, d_1506=1, d_1507=0, d_1508=1, d_1509=0, d_1510=0, d_1511=1, d_1512=1, d_1513=1, d_1514=2, d_1515=1, d_1516=1, d_1517=1, d_1518=0, d_1519=2, d_1520=2, d_1521=2, d_1522=1, d_1523=0, d_1524=0, d_1525=0, d_1526=1, d_1527=2, d_1528=0, d_1529=0, d_1530=1, d_1531=2, d_1532=1, d_1533=1, d_1534=1, d_1535=0, d_1536=1, d_1537=0, d_1538=1, d_1539=0, d_1540=0, d_1541=1, d_1542=0, d_1543=1, d_1544=0, d_1545=2, d_1546=1, d_1547=0, d_1548=2, d_1549=0, d_1550=1, d_1551=0, d_1552=0, d_1553=0, d_1554=1, d_1555=1, d_1556=2, d_1557=0, d_1558=0, d_1559=0, d_1560=0, d_1561=0, d_1562=0, d_1563=0, d_1564=0, d_1565=0, d_1566=0, d_1567=0, d_1568=0, d_1569=0, d_1570=0, d_1571=0, d_1572=0, d_1573=0, d_1574=0, d_1575=0, d_1576=0, d_1577=0, d_1578=0, d_1579=0, d_1580=0, d_1581=0, d_1582=0, d_1583=0, d_1584=0, d_1585=0, d_1586=0, d_1587=0, d_1588=0, d_1589=0, d_1590=0, d_1591=1, d_1592=1, d_1593=0, d_1594=0, d_1595=0, d_1596=0, d_1597=0, d_1598=0, d_1599=0, d_1600=0, d_1601=0, d_1602=1, d_1603=3, d_1604=1, d_1605=1, d_1606=0, d_1607=1, d_1608=1, d_1609=0, d_1610=0, d_1611=0, d_1612=1, d_1613=1, d_1614=2, d_1615=0, d_1616=0, d_1617=0, d_1618=1, d_1619=0, d_1620=2, d_1621=1, d_1622=0, d_1623=1, d_1624=1, d_1625=0, d_1626=0, d_1627=0, d_1628=1, d_1629=1, d_1630=1, d_1631=3, d_1632=1, d_1633=1, d_1634=0, d_1635=0, d_1636=2, d_1637=0, d_1638=1, d_1639=0, d_1640=0, d_1641=0, d_1642=2, d_1643=0, d_1644=0, d_1645=0, d_1646=4, d_1647=2, d_1648=1, d_1649=0, d_1650=0, d_1651=0, d_1652=0, d_1653=2, d_1654=1, d_1655=0, d_1656=1, d_1657=1, d_1658=0, d_1659=0, d_1660=0, d_1661=1, d_1662=2, d_1663=1, d_1664=1, d_1665=0, d_1666=0, d_1667=2, d_1668=0, d_1669=2, d_1670=2, d_1671=0, d_1672=0, d_1673=0, d_1674=1, d_1675=1, d_1676=0, d_1677=2, d_1678=0, d_1679=1, d_1680=1, d_1681=2, d_1682=0, d_1683=1, d_1684=0, d_1685=0, d_1686=0, d_1687=2, d_1688=1, d_1689=0, d_1690=1, d_1691=1, d_1692=2, d_1693=0, d_1694=0, d_1695=0, d_1696=0, d_1697=0, d_1698=0, d_1699=0, d_1700=1, d_1701=0, d_1702=1, d_1703=0, d_1704=1, d_1705=0, d_1706=3, d_1707=1, d_1708=1, d_1709=0, d_1710=1, d_1711=1, d_1712=2, d_1713=0, d_1714=0, d_1715=0, d_1716=0, d_1717=1, d_1718=1, d_1719=0, d_1720=0, d_1721=0, d_1722=0, d_1723=3, d_1724=0, d_1725=1, d_1726=0, d_1727=0, d_1728=0, d_1729=0, d_1730=1, d_1731=1, d_1732=1, d_1733=0, d_1734=1, d_1735=0, d_1736=2, d_1737=0, d_1738=0, d_1739=0, d_1740=0, d_1741=2, d_1742=0, d_1743=0, d_1744=0, d_1745=0, d_1746=1, d_1747=1, d_1748=2, d_1749=0, d_1750=0, d_1751=0, d_1752=0, d_1753=2, d_1754=0, d_1755=0, d_1756=1, d_1757=1, d_1758=1, d_1759=1, d_1760=0, d_1761=0, d_1762=0, d_1763=0, d_1764=0, d_1765=1, d_1766=2, d_1767=2, d_1768=0, d_1769=1, d_1770=0, d_1771=0, d_1772=0, d_1773=0, d_1774=1, d_1775=2, d_1776=1, d_1777=0, d_1778=0, d_1779=0, d_1780=0, d_1781=0, d_1782=1, d_1783=0, d_1784=3, d_1785=0, d_1786=1, d_1787=2, d_1788=1, d_1789=0, d_1790=3, d_1791=0, d_1792=0, d_1793=0, d_1794=1, d_1795=0, d_1796=2, d_1797=2, d_1798=1, d_1799=0, d_1800=0, d_1801=1, d_1802=2, d_1803=0, d_1804=1, d_1805=0, d_1806=1, d_1807=4, d_1808=0, d_1809=0, d_1810=5, d_1811=0, d_1812=0, d_1813=0, d_1814=0, d_1815=0, d_1816=0, d_1817=2, d_1818=1, d_1819=2, d_1820=1, d_1821=0, d_1822=0, d_1823=0, d_1824=1, d_1825=1, d_1826=1, d_1827=0, d_1828=0, d_1829=1, d_1830=1, d_1831=1, d_1832=1, d_1833=1, d_1834=0, d_1835=0, d_1836=0, d_1837=2, d_1838=2, d_1839=0, d_1840=0, d_1841=1, d_1842=4, d_1843=0, d_1844=0, d_1845=0, d_1846=0, d_1847=1, d_1848=1, d_1849=2, d_1850=0, d_1851=4, d_1852=0, d_1853=1, d_1854=0, d_1855=1, d_1856=4, d_1857=2, d_1858=0, d_1859=2, d_1860=0, d_1861=1, d_1862=1, d_1863=0, d_1864=1, d_1865=0, d_1866=0, d_1867=1, d_1868=1, d_1869=3, d_1870=0, d_1871=0, d_1872=0, d_1873=1, d_1874=1, d_1875=1, d_1876=3, d_1877=1, d_1878=3, d_1879=1, d_1880=2, d_1881=2, d_1882=0, d_1883=1, d_1884=1, d_1885=1, d_1886=1, d_1887=0, d_1888=0, d_1889=0, d_1890=0, d_1891=0, d_1892=1, d_1893=0, d_1894=4, d_1895=2, d_1896=3, d_1897=0, d_1898=1, d_1899=2, d_1900=0, d_1901=0, d_1902=0, d_1903=1, d_1904=1, d_1905=3, d_1906=0, d_1907=1, d_1908=1, d_1909=1, d_1910=3, d_1911=0, d_1912=1, d_1913=1)

In [10]:
price_df = pd.read_csv(os.path.join(DATA_ROOT, "sell_prices.csv"))
price_df.head(3)

  store_id        item_id  wm_yr_wk  sell_price
0     CA_1  HOBBIES_1_001     11325        9.58
1     CA_1  HOBBIES_1_001     11326        9.58
2     CA_1  HOBBIES_1_001     11327        8.26

In [11]:
eval_df = pd.read_csv(os.path.join(DATA_ROOT, "sales_train_evaluation.csv"))
eval_df.head(3)

,id,item_id,dept_id,cat_id,store_id,state_id,d_1,d_2,d_3,d_4,...,d_1932,d_1933,d_1934,d_1935,d_1936,d_1937,d_1938,d_1939,d_1940,d_1941
0,HOBBIES_1_001_CA_1_evaluation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,2,4,0,0,0,0,3,3,0,1
1,HOBBIES_1_002_CA_1_evaluation,HOBBIES_1_002,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,0,1,2,1,1,0,0,0,0,0
2,HOBBIES_1_003_CA_1_evaluation,HOBBIES_1_003,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,1,0,2,0,0,0,2,3,0,1